/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testLengthMethod(){
        assertEquals(
                "The array should be 3 long",
                3,
                Library.roll(3).length
        );
    }

    @Test public void dupTrue(){
        assertEquals(
                "The array has duplicate, should return true",
                true,
                Library.containsDuplicates(new int[]{1, 1})
        );
    }

    @Test public void dupFalse(){
        assertEquals(
                "the array has no duplicates, should return false",
                false,
                Library.containsDuplicates(new int[]{1, 2, 3, 4})
        );
    }

    @Test public void arrAvg(){
        assertEquals(
                "The average should be 2",
                2.0f,
                Library.arrAvg(new int[]{1, 2, 3}),
                0.05f
        );
    }

    @Test public void arrNotAvg(){
        assertNotEquals(
                "The average should be 2, but is not",
                3.0f,
                Library.arrAvg(new int[]{1, 2, 3}),
                        0.05f
        );
    }

    @Test public void arrArrlength(){
        int[][] testArr = {
                {1, 2, 1, 2, 1, 2},
                {3, 4, 3, 4, 3, 4},
                {5, 6, 5, 6, 5, 6}
        };
        assertArrayEquals(
                "Should return an array of [1.5, 3.5, 5.5]",
                new float[]{1.5f, 3.5f, 5.5f},
                Library.arrAvgLots(testArr),
                0.05f
        );
    }

    @Test public void arrArrDifflength(){
        int[][] testArr = {
                {1, 2, 1, 2, 1, 2, 1, 2},
                {3, 4, 3, 4},
                {5, 6, 5, 6, 5, 6}
        };
        assertArrayEquals(
                "Should return an array of [1.5, 3.5, 5.5]",
                new float[]{1.5f, 3.5f, 5.5f},
                Library.arrAvgLots(testArr),
                0.05f
        );
    }

    @Test public void arrAvgLowest(){
        int[][] testArr = {
                {1, 2, 1, 2, 1, 2, 1, 2},
                {3, 4, 3, 4},
                {5, 6, 5, 6, 5, 6}
        };
        assertArrayEquals(
                "Should return [1, 2, 1, 2, 1, 2, 1, 2]",
                new int[]{1, 2, 1, 2, 1, 2, 1, 2},
                Library.arrAvgLow(testArr)
        );
    }
}
