/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int randomInt(int min, int max) {
        Random random = new Random();
        int randomInt = random.nextInt((max - min) + 1) + min;
        return randomInt;
    }

    public static int[] roll(int rollsNum){
        int[] rollsArr = new int[rollsNum];
        for(int i = 0; i < rollsArr.length; i++){
            rollsArr[i] = randomInt(0,6);
        }
        return rollsArr;
    }

    public static boolean containsDuplicates(int[] arrIn){
        boolean duplicate = false;

        for(int i = 0; i < arrIn.length; i++){
            for(int j = 0; j < arrIn.length; j++){
                if(arrIn[i] == arrIn[j] && i != j){
                    duplicate = true;
                }
            }
        }

        return duplicate;
    }

    public static float arrAvg(int[] arrIn){
        float total = 0;

        for(int i = 0; i < arrIn.length; i++){
            total += arrIn[i];
        }

        return (total/((float)arrIn.length));
    }

    public static float[] arrAvgLots(int[][] arrIn){
        float[] arrOut = new float[arrIn.length];

        for(int i = 0; i < arrIn.length; i++){
            arrOut[i] = arrAvg(arrIn[i]);
        }

        return arrOut;
    }
}
